---
title: Worko
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: false
  uploads:
    title: Uploads
    output: true
name: Worko
markdown: kramdown
highlighter: rouge
exclude:
- node_modules
- gulpfile.js
- package.json
- src
port: 4000
gems:
- jekyll-language-plugin
sass:
  style: :compressed
languages:
- en
- fr
language_data: data.lang.%%
language_includes_dir: _i18n
